[project]
name = "omnipart"
description = "OmniPart: Part-Aware 3D Generation with Semantic Decoupling and Structural Cohesion,this node ,you can use it in comfyUI"
version = "1.0.0"
license = {file = "LICENSE"}
dependencies = ["torch", "torchvision", "pillow", "imageio", "imageio-ffmpeg", "tqdm", "easydict", "opencv-python-headless", "scipy", "rembg", "onnxruntime", "trimesh", "xatlas", "pyvista", "pymeshfix", "igraph", "git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8", "xformers", "spconv-cu120", "transformers", "pydantic", "diffusers", "lightning", "mesh2sdf", "loguru", "tetgen", "pymeshfix", "igraph", "omegaconf", "pycocotools", "kornia", "timm", "h5py", "boto3", "torch-scatter", "git+https://github.com/facebookresearch/segment-anything.git", "git+https://github.com/facebookresearch/detectron2.git", "#https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.0.post2/flash_attn-2.7.0.post2+cu12torch2.4cxx11abiFALSE-cp310-cp310-linux_x86_64.whl", "#https://huggingface.co/spaces/JeffreyXiang/TRELLIS/resolve/main/wheels/diff_gaussian_rasterization-0.0.0-cp310-cp310-linux_x86_64.whl?download=true", "#https://huggingface.co/spaces/JeffreyXiang/TRELLIS/resolve/main/wheels/nvdiffrast-0.3.3-cp310-cp310-linux_x86_64.whl?download=true"]

[project.urls]
Repository = "https://github.com/smthemex/ComfyUI_OmniPart"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "smthemex"
DisplayName = "ComfyUI_OmniPart"
Icon = ""
includes = []
